target_estimator_node:
    ros__parameters:
      shoulder_scale: 405.014
      shoulder_offset: -0.314
      torso_scale: 697.526
      torso_offset: -0.239
      max_shoulder_range_hold_time: 0.3
      min_distance: 0.3
      max_distance: 5.0
      measurement_median_window: 3
